"""Compatibility facade — prefer importing from focused modules directly over time."""

from bot_config import (
    ALLOWED_CHANNEL_ID,
    CHALLENGE_TIMEOUT_SECONDS,
    CURRENCY_NAME,
    CURRENCY_SYMBOL,
    DAILY_AMOUNT,
    LOG_CHANNEL_ID,
    MATCH_ACCEPTED_TIMEOUT_SECONDS,
    MATCH_ACTIVE_TIMEOUT_SECONDS,
    MATCH_REWARD,
    MIN_BATTLE_WAGER,
    MIN_TEAM_BET,
    MODERATOR_ROLE_ID,
    QUEUE_CHANNEL_IDS,
    STARTING_BALANCE,
    TEAM_MATCH_ACTIVE_TIMEOUT_SECONDS,
    TEAM_MATCH_OPEN_TIMEOUT_SECONDS,
    TOP_PAGE_SIZE,
)
from bot_runtime import (
    ensure_user,
    fmt,
    fmt_user,
    gen_id,
    get_bot,
    get_db_pool,
    get_user,
    log,
    now_utc,
    set_bot,
    set_db_pool,
    spendable,
    ts,
)
from bot_schema import init_database
from bot_queue import parse_team_mentions, reward_queue_match
from bot_ledger import (
    InsufficientFundsError,
    PayoutReverseError,
    burn_escrow,
    cancel_match_if_pending,
    cancel_open_match_with_refunds,
    cancel_team_match_with_refunds,
    complete_match_if_active,
    credit,
    debit_escrow,
    lock_match,
    lock_user,
    lock_users_ordered,
    propose_or_confirm_winner,
    release_escrow,
    release_escrow_up_to,
    restore_match_to_pre_payout,
    restore_team_match_to_pre_payout,
    run_payout,
    run_team_match_payout,
    settle_pari_mutuel_bets,
)
from bot_presentation import (
    build_accepted_match_embed,
    build_cancelled_match_embed,
    build_open_matches_embed,
    build_team_match_embed,
    build_top_embed,
    enforce_channel,
    find_open_match_between,
    find_open_team_match_between,
    get_display_name,
    get_role_mention,
    get_team_bet_totals,
    has_mod_role,
    lock_team_match,
    member_has_mod_role,
    resolve_role_label,
    resolve_user_label,
    update_match_message,
    update_team_match_message,
)

__all__ = [name for name in globals() if not name.startswith("_")]
